### ISSUE TITLE
Fetch silent

### ISSUE THREAD

**Issue by Joachim96** [Cytomine-ULiege/Cytomine-python-client#12]
Hello, 

Is there a way to fetch without causing it to print the GET and HTTP response code? I didn't find this in the doc.

Thank you very much

**Comment by urubens** [comment]
Hi,

Yes, when you connect to Cytomine client, you can set the verbosity:

```
import logging
Cytomine.connect(host, pub, priv, verbose=logging.NOTSET)
```

See https://docs.python.org/3.6/library/logging.html#logging-levels for other log levels.
