### ISSUE TITLE
Method `window` of the class ImageInstance crashes when `dest_pattern` is not set

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-python-client#17]
Hello,

I found a bug in the function window() while using it.
https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/master/cytomine/models/image.py#L295

The bug crashes the script when we do not provide a path to the optional dest_pattern parameter.
However the function works fine if we provide a path.

**Comment by urubens** [comment]
Hi,

Thanks for reporting this issue. Fixed by 984c0dc56cb407b0d73251f476c75d4aa0b8c440
