### ISSUE TITLE
Error on callback_identifier in model with softwareparameter

### ISSUE THREAD

**Issue by ggekos** [Cytomine-ULiege/Cytomine-python-client#22]
the callback_identifier return softwareparameter,so that result in a 404.
The callback_identifier should return software_parameter .

https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/5735bbb17b7a97daea9f667a68a23e589906fe09/cytomine/models/model.py#L110

**Comment by urubens** [comment]
Which edition of Cytomine are you using ? 
In Cytomine ULiege Edition, the callback identifier has always been `softwareparameter`. This fork of the Cytomine-python-client is intended to work well with this ULiege Edition.

Cytomine Community Edition (@cytomine) recently introduced `software_parameter` but the old `sofwareparameter` seems to be still accepted for backward compatibility.
