### ISSUE TITLE
Sunset v1 deprecated methods and drop support

### ISSUE THREAD

**Issue by urubens** [Cytomine-ULiege/Cytomine-python-client#24]
A lot of deprecated methods from Cytomine-python-client v1.x are still supported. However, these are no more updated (for example `add_image_group` for which the meaning has changed since), and the deprecation is running for nearly 4 years (January 2018).

Are there any scripts or applications that still use v1.x methods ? 
We should decide on a sunset date or a sunset version (v3.x ?)

By the way, Python 2 is deprecated since January 2020. I'm in favor of dropping its support in a future release, as it will simplify the code base (no more `future` and `six` workarounds).

**Comment by bathienle** [comment]
done by commit 358ab6b2c8f34415c09513996aab0765f17e9ada
