### ISSUE TITLE
2.8.3 version of package in private index is not up to date with current master since more than 1 year

### ISSUE THREAD

**Issue by bedohazizsolt** [Cytomine-ULiege/Cytomine-python-client#34]
Private index: https://packagecloud.io/cytomine-uliege/Cytomine-python-client/pypi/simple cytomine-python-client

2.8.3 version of package in private index was released more than 1 year ago, and it did not reflect the status, changes in current master.

Please create new release in the private index if possible.

**Comment by bathienle** [comment]
Hello,

A new version (2.9.0) with the changes on the master branch was released at https://packagecloud.io/cytomine-uliege/Cytomine-python-client.
