### ISSUE TITLE
Make save() more generic by auto-detecting existence of an object

### ISSUE THREAD

**Issue by waliens** [Cytomine-ULiege/Cytomine-python-client#5]
Could have:
- `object.create()`: create the object (if no id is present, otherwise throws an error)
- `object.update()`: update the object (if an id is present, otherwise throws an error)
- `object.save()`: create or update based on the absence or presence of an id

**Comment by waliens** [comment]
@urubens is this done ?

**Comment by urubens** [comment]
Not yet :disappointed:
